### PR TITLE
refactor: use private fields and methods for SaveParser_Read

### PR DESCRIPTION
**Pull request by RebeccaStevens**
This looks like a big change but all it is going it renaming fields and methods.
It simple prefixes each private method and field (which in this case is all of them) with "#".

Re: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

It also adds types via JSDoc comments and the .d.ts file.

### CODE REVIEW

**Comment by RebeccaStevens** [comment]
Note: there seems to be a bunch of whitespaces changes. I'm not sure why but if I was to guess, I would say it's probably line ends change from windows style to unix style.

So when reviewing the changes, you'll probably want to hide whitespaces change (you can just amend `?w=1` to the url to do this).

Do you want to resolve line ending issues going forward?

**Comment by AnthorNet** [comment]
Gosh I hate the # proposal :D
I'm looking at the end lines, I believe it might be a problem on my side when I switched working laptop :S

**Comment by RebeccaStevens** [comment]
Whitespace issues seem fixed now

**Comment by AnthorNet** [comment]
Will pass on that one as I don't see any real benefits to it.

**Comment by RebeccaStevens** [comment]
All good. I'll try better to catch myself making random unnecessary changes like this. I've caught myself a few times but it slipped through here.

**Pull request closed without merging**
